# Get docker for your system @ https://docs.docker.com/get-docker/
#   Docker for Linux
#   Docker Desktop for Windows / macOS
# 
# Use the following commands to start the cluster
#   Starting:
#     $ docker-compose -f docker-compose-cluster.yml up
#   Deleteing all ZooKeeper sanpshots:
#     $ docker-compose -f docker-compose-cluster.yml down -v 

version: '2'

services:
  zookeeper1:
    image: docker.io/zookeeper:3.7
    hostname: zoo1.zk.local
    ports:
      - 2181:2181
    networks:
      - zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes
  
  zookeeper2:
    image: docker.io/zookeeper:3.7
    hostname: zoo2.zk.local
    ports:
      - 2182:2181
    networks:
      - zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes
  
  zookeeper3:
    image: docker.io/zookeeper:3.7
    hostname: zoo3.zk.local
    ports:
      - 2183:2181
    networks:
      - zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1.zk.local:2888:3888;2181 server.2=zoo2.zk.local:2888:3888;2181 server.3=zoo3.zk.local:2888:3888;2181
      ALLOW_ANONYMOUS_LOGIN: yes
  
#  zoonavigator:
#    image: elkozmon/zoonavigator:1.1.1
#    hostname: navigator.zk.local
#    ports:
#      - 9000:9000
#    networks:
#      - zookeeper
#    environment:
#      HTTP_PORT: 9000
#      CONNECTION_ZKLOCAL1_NAME: ZooKeeper Server 1
#      CONNECTION_ZKLOCAL1_CONN: zoo1.zk.local
#
#      CONNECTION_ZKLOCAL2_NAME: ZooKeeper Server 2
#      CONNECTION_ZKLOCAL2_CONN: zoo2.zk.local
#
#      CONNECTION_ZKLOCAL3_NAME: ZooKeeper Server 3
#      CONNECTION_ZKLOCAL3_CONN: zoo3.zk.local
#
#      AUTO_CONNECT_CONNECTION_ID: ZKLOCAL1

networks:
  zookeeper:
    name: custom_network