# Get docker for your system @ https://docs.docker.com/get-docker/
#   Docker for Linux
#   Docker Desktop for Windows / macOS
# 
# Use the following commands to start the cluster
#   Starting:
#     $ docker-compose -f docker-compose-cluster.yml up
#   Deleteing all ZooKeeper sanpshots:
#     $ docker-compose -f docker-compose-cluster.yml down -v 

version: '2'

services:
  server1:
    image: txn-mngr
    hostname: server1.local
    ports:
      - '8081:8080' # For REST
      - '8981:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server1.local'

  server2:
    image: txn-mngr
    hostname: server2.local
    ports:
      - '8082:8080' # For REST
      - '8982:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server2.local'

  server3:
    image: txn-mngr
    hostname: server3.local
    ports:
      - '8083:8080' # For REST
      - '8983:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server3.local'

  server4:
    image: txn-mngr
    hostname: server4.local
    ports:
      - '8084:8080' # For REST
      - '8984:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server4.local'

  server5:
    image: txn-mngr
    hostname: server5.local
    ports:
      - '8085:8080' # For REST
      - '8985:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server5.local'

  server6:
    image: txn-mngr
    hostname: server6.local
    ports:
      - '8086:8080' # For REST
      - '8986:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server6.local'

  server7:
    image: txn-mngr
    hostname: server7.local
    ports:
      - '8087:8080' # For REST
      - '8987:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server7.local'

  server8:
    image: txn-mngr
    hostname: server8.local
    ports:
      - '8088:8080' # For REST
      - '8988:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server8.local'

  server9:
    image: txn-mngr
    hostname: server9.local
    ports:
      - '8089:8080' # For REST
      - '8989:8980' # For gRPC
    networks:
      - zookeeper
    env_file:
      - 'variables.env'
    environment:
      HOST_NAME: 'server9.local'

networks:
  zookeeper:
    external:
      name: custom_network